name: MedPanel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-patients:
    name: Test mfe-patients
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: mfe-patients/package-lock.json
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        working-directory: mfe-patients
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run tests
        working-directory: mfe-patients
        run: npm run test:run

  build-mfes:
    name: Build MFEs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mfe: [mfe-dashboard, mfe-patients, mfe-appointments, shell-app]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: ${{ matrix.mfe }}/package-lock.json
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        working-directory: ${{ matrix.mfe }}
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        working-directory: ${{ matrix.mfe }}
        run: npm run build
        env:
          VITE_DASHBOARD_URL: https://medpanel-dashboard.vercel.app
          VITE_PATIENTS_URL: https://medpanel-patients.vercel.app
          VITE_APPOINTMENTS_URL: https://medpanel-appointments.vercel.app
